// -------------------read this to understand
// User → SQL Agent → Guardrail → Guardrail Agent → Allow / Block

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// process.env.OPENAI_AGENTS_DISABLE_TRACING = "true";
// // disables SDK tracing logs so console stays clean

// import "dotenv/config";
// // loads environment variables from .env

// import { Agent, run, OutputGuardrailTripwireTriggered } from "@openai/agents";
// // Agent → create AI agents
// // run → execute an agent
// // OutputGuardrailTripwireTriggered → error when guardrail blocks output

// import { z } from "zod";
// // used to define structured outputs for agents

// // Gatekeeper Output Guardrail
// const sqlGuardrail = {
//   name: "SQL Guardrail",

//   async execute({ agentOutput }) {

//     console.log("⚡ Guardrail Triggered   ----------------1");
//     // means SQL agent finished and guardrail started

//     console.log(
//       "Generated SQL Query:====================== 2",
//       agentOutput.sqlQuery,
//     );
//     // logs the SQL query generated by the SQL Agent

//     const result = await run(sqlGuardrailAgent, agentOutput.sqlQuery);
//     // sends generated SQL query to guardrail agent for safety check

//     console.log(
//       "Guardrail Decision:======================== 3",
//       result.finalOutput,
//     );
//     // shows guardrail agent response {reason, isSafe}

//     console.log(
//       "Is Query Safe:============================ 4",
//       result.finalOutput.isSafe,
//     );
//     // prints true or false

//     return {
//       outputInfo: result.finalOutput.reason,
//       // message explaining why query is unsafe

//       tripwireTriggered: !result.finalOutput.isSafe,
//       // if query unsafe → tripwire = true → block output
//     };
//   },
// };

// // Guardrail Agent (AI that checks query safety)
// const sqlGuardrailAgent = new Agent({
//   name: "SQL Guardrail Agent",

//   instructions: `Check if the SQL query is safe.
//   you only allow to read and not delete, update or modify the data in any way.`,
//   // tells the model to allow only read queries

//   model: "openai/gpt-4o",

//   outputType: z.object({
//     reason: z.string().describe("Reason why the query is unsafe"),
//     // explanation if query is unsafe

//     isSafe: z.boolean().describe("Whether the query is safe"),
//     // true if safe, false if dangerous
//   }),
// });

// // Main SQL Agent (generates SQL queries)
// const sqlAgent = new Agent({
//   name: "SQL EXPERT Agent",

//   instructions: `You are an expert SQL agent specialised in generating SQL queries.
//   Database Schema: ...`,
//   // gives schema so agent can write correct SQL

//   model: "openai/gpt-4o",

//   outputType: z.object({
//     sqlQuery: z.string().describe("SQL query generated by the agent"),
//   }),
//   // ensures the agent returns a SQL query string

//   outputGuardrails: [sqlGuardrail],
//   // attaches guardrail that checks the generated SQL
// });

// // Main function (user query entry point)
// async function main(q = "") {

//   console.log("🚀 Running SQL Agent::::::::::::::::: 5");
//   // shows program started

//   console.log("User Query:::::::::::::::::: 6", q);
//   // logs user question

//   const result = await run(sqlAgent, q);
//   // runs SQL agent → generates SQL → guardrail checks it

//   console.log("✅ SQL Agent Finished---------7");
//   // indicates process completed

//   console.log("Final SQL Query:::::::::::::: 8", result.finalOutput.sqlQuery);
//   // prints final allowed SQL query
// }

// main("delete all users with their comments");
// // main("get all users with their comments");

process.env.OPENAI_AGENTS_DISABLE_TRACING = "true";
import "dotenv/config";
import { Agent, run, OutputGuardrailTripwireTriggered } from "@openai/agents";
import { z } from "zod";

//Gatekeeper Output  Guardrail
const sqlGuardrail = {
  name: "SQL Guardrail",

  async execute({ agentOutput }) {
    console.log("⚡ Guardrail Triggered   ----------------1");
    console.log(
      "Generated SQL Query:====================== 2",
      agentOutput.sqlQuery,
    );

    const result = await run(sqlGuardrailAgent, agentOutput.sqlQuery);

    console.log(
      "Guardrail Decision:======================== 3",
      result.finalOutput,
    );
    console.log(
      "Is Query Safe:============================ 4",
      result.finalOutput.isSafe,
    );

    return {
      outputInfo: result.finalOutput.reason,
      tripwireTriggered: !result.finalOutput.isSafe,
    };
  },
};

//  Agent (Guardrail Agent)
const sqlGuardrailAgent = new Agent({
  name: "SQL Guardrail Agent",
  instructions: `Check if the SQL query is safe.
  you only allow to read and not delete, update or modify the data in any way.`,

  model: "openai/gpt-4o",
  outputType: z.object({
    reason: z.string().describe("Reason why the query is unsafe"),
    isSafe: z.boolean().describe("Whether the query is safe"),
  }),
});

// SQL Agent
const sqlAgent = new Agent({
  name: "SQL EXPERT Agent",
  instructions: `You are an expert SQL agent specialised in generating SQL queries.

Database Schema:

CREATE TABLE users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE comments (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);`,
  model: "openai/gpt-4o",

  outputType: z.object({
    sqlQuery: z.string().describe("SQL query generated by the agent"),
  }),

  outputGuardrails: [sqlGuardrail],
});

// Main function- user query
async function main(q = "") {
  console.log("🚀 Running SQL Agent::::::::::::::::: 5");
  console.log("User Query:::::::::::::::::: 6", q);

  const result = await run(sqlAgent, q);

  console.log("✅ SQL Agent Finished---------7");
  console.log("Final SQL Query:::::::::::::: 8", result.finalOutput.sqlQuery);
}

main("delete all users with their comments");
// main("get all users with their comments");
